import { Geist, Geist_Mono, Margarine } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav
          style={{
            width: "100%",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            backgroundColor: "teal",
          }}
        >
          <Link style={{ margin: "0 10px", color: "white" }} href="/">
            Home
          </Link>
          <Link style={{ margin: "0 10px", color: "white" }} href="/articales">
            Articales
          </Link>
          <Link style={{ margin: "0 10px", color: "white" }} href="/posts">
            Posts
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
